name: ds23
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - scikit-learn
  - statsmodels
  - jupyter
  - jupyterlab
  - notebook
  - ipython
  - ipykernel
  - tensorflow
  - keras
  - pytorch
  - u8darts-all
  - torchvision
  - torchaudio
  - xgboost
  - lightgbm
  - catboost
  - nltk
  - spacy
  - plotly
  - bokeh
  - joblib
  - tqdm
  - pip
  - pip:
    - opencv-python
    - imbalanced-learn
    - streamlit
